import numpy as np
import matplotlib.pyplot as plt


class Experiment:
    def __init__(self):
        self.simulate_beta_0_mean = np.random.rand(1)[0] + 1e-10
        self.simulate_beta_1_mean = np.random.rand(1)[0] + 1
        self.beta_0 = 0
        self.beta_1 = 0
        pass

    def M(self, x):
        return self.beta_0 + self.beta_1 * x

    def groundtruth(self, alpha_):
        return (alpha_ - self.simulate_beta_0_mean)/self.simulate_beta_1_mean


    def generate(self, x):
        """
        set F(x) the uniform distribution over [0,1]
        :param x: an approximation generated by the method
        :return: a sample from the distribution
        """
        # distributed on [self.simulate_beta_0_mean - 0.5, self.simulate_beta_0_mean + 0.5)
        self.beta_0 = np.random.rand(1)[0] + self.simulate_beta_0_mean - 0.5
        # distributed on [self.simulate_beta_1_mean - 0.5, self.simulate_beta_0_mean + 0.5)
        self.beta_1 = np.random.rand(1)[0] + self.simulate_beta_1_mean - 0.5
        return self.M(x)


class RobbinsMonroMethod:
    def __init__(self, repeat_times_=1000, method_type_='single', batch_size_=10):
        self.method_type = method_type_
        self.repeat_times = repeat_times_
        self.batch_size_ = 1 if method_type_ == 'single' else batch_size_
        pass

    def run(self, alpha_):
        x = np.random.rand(1)[0]
        expectation_log = []
        experiment = Experiment()
        for i in range(1, self.repeat_times):
            y = [experiment.generate(x) for _ in range(self.batch_size_)]
            y = np.array(y).mean()
            x = x + 1 / i * (alpha - y)
            expectation_log.append(x)
        return expectation_log, experiment.groundtruth(alpha_)


if __name__ == '__main__':
    alpha = 0.4
    rbm = RobbinsMonroMethod(method_type_='batch')
    expectation_log, gt = rbm.run(alpha)
    # print('current expectation: ' + str(expectation_log[-1]))
    plt.plot(expectation_log, linewidth=1)
    plt.plot([1, 1000], [gt, gt], linestyle=":", linewidth=1)
    plt.show()
